package p1admin.adminview;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.ListModel;

import p1admin.admincontroller.AllQuestionsController;
import p1admin.model.Pregunta;

/**
 * Interfaz de la ventana principal.
 *
 * @author Manuel Montenegro (mmontene@ucm.es)
 */
public class AllQuestionsEditor extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
	private final AllQuestionsController controller;

    public AllQuestionsEditor(ListModel<Pregunta> model, AllQuestionsController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
        listaPreguntas = new JList<>();
        scrollPreguntas.setViewportView(listaPreguntas);
        listaPreguntas.setCellRenderer(new QuestionCellRenderer());
        listaPreguntas.setModel(model);
        final JDialog that = this;
        listaPreguntas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = listaPreguntas.locationToIndex(e.getPoint());
                    controller.updateQuestion(model.getElementAt(index), that);
                    listaPreguntas.repaint();
                }
            }
            
        });
        controller.gatherAllQuestions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        botonAnyadir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        labelFiltro = new javax.swing.JLabel();
        textFiltro = new javax.swing.JTextField();
        scrollPreguntas = new javax.swing.JScrollPane();
        buttonFiltro = new javax.swing.JButton();

        setTitle("Editor de preguntas");

        botonAnyadir.setMnemonic('A');
        botonAnyadir.setText("Añadir pregunta");
        botonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnyadirActionPerformed(evt);
            }
        });
        panelBotones.add(botonAnyadir);

        botonEliminar.setMnemonic('E');
        botonEliminar.setText("Eliminar pregunta");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        panelBotones.add(botonEliminar);

        labelFiltro.setDisplayedMnemonic('F');
        labelFiltro.setLabelFor(textFiltro);
        labelFiltro.setText("Filtrar por enunciado:");

        buttonFiltro.setMnemonic('F');
        buttonFiltro.setText("Filtrar");
        buttonFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPreguntas)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFiltro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFiltro)
                    .addComponent(textFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnyadirActionPerformed
        controller.newQuestion(this);
        listaPreguntas.repaint();
    }//GEN-LAST:event_botonAnyadirActionPerformed

    private void buttonFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltroActionPerformed
        String text = textFiltro.getText();
        if (text != null && !text.trim().isEmpty()) {
            controller.findByName(text.trim());
        } else {
            controller.gatherAllQuestions();
        }
    }//GEN-LAST:event_buttonFiltroActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        Pregunta selected = listaPreguntas.getSelectedValue();
        if (selected != null) {
            controller.removeQuestion(selected);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnyadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton buttonFiltro;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JScrollPane scrollPreguntas;
    private javax.swing.JTextField textFiltro;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JList<Pregunta> listaPreguntas;
}
