/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1admin.adminview;

import p1admin.model.Pregunta;

/**
 * Vista de cada una de las preguntas en el JList de la ventana principal.
 * 
 * @author Manuel Montenegro (mmontene@ucm.es)
 */
public class QuestionPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
    }
    
    public void setElement(Pregunta elem) {
        String statement = elem.getEnunciado();
        Integer numAnswers = elem.getOpciones().size();
        this.labelQuestion.setText(statement);
        this.labelNumOptions.setText(numAnswers.toString() + " opciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelQuestion = new javax.swing.JLabel();
        labelNumOptions = new javax.swing.JLabel();

        labelQuestion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelQuestion.setText("Pregunta");

        labelNumOptions.setText("n opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(labelNumOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumOptions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNumOptions;
    private javax.swing.JLabel labelQuestion;
    // End of variables declaration//GEN-END:variables
}
