/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

/**
 *
 * @author adrianpanaderogonzalez
 */
public class ElementoListaPreguntas extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String enunciado = "Enunciado";
    private int numeroOpciones = 3;

    /**
     * Creates new form ElementoListaPreguntas
     */
    public ElementoListaPreguntas() {
        initComponents();
    }
    
    public String getEnunciado() {
		return enunciado;
	}

	public void setEnunciado(String enunciado) {
		this.enunciado = enunciado;
                labelEnunciado.setText(enunciado);
	}

	public int getNumeroOpciones() {
		return numeroOpciones;
	}

	public void setNumeroOpciones(int numeroOpciones) {
		this.numeroOpciones = numeroOpciones;
                labelNumOpciones.setText(numeroOpciones + " opciones");
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEnunciado = new javax.swing.JLabel();
        labelNumOpciones = new javax.swing.JLabel();

        labelEnunciado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEnunciado.setForeground(new java.awt.Color(51, 51, 51));
        labelEnunciado.setText("Enunciado");

        labelNumOpciones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelNumOpciones.setForeground(new java.awt.Color(51, 51, 51));
        labelNumOpciones.setText("3 opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(labelNumOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumOpciones)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelEnunciado;
    private javax.swing.JLabel labelNumOpciones;
    // End of variables declaration//GEN-END:variables
}
