/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.LoginController;
import abd.p1.controller.UserController;
import abd.p1.model.CalculadorDistancias;
import abd.p1.model.Usuario;
import abd.p1.model.ValidadorEmail;

import java.util.List;
import java.util.Set;

import javax.swing.JOptionPane;

import org.hibernate.SessionFactory;
	
/**
 *
 * @author adrianpanaderogonzalez
 */
@SuppressWarnings("serial")
public class VentanaLogin extends java.awt.Dialog {
    
    private LoginController control;
    private UserController controlUsuarios;
    private SessionFactory sesion;
    private boolean login;
    private Usuario usuario;
    /**
     * Creates new form NewDialog
     * @param cU 
     */
    public VentanaLogin(java.awt.Frame parent, boolean modal, SessionFactory sf, UserController cU) {
        super(parent, modal);
        this.sesion = sf;
        login = false;
        control = new LoginController(sesion);
        controlUsuarios = cU;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonNuevoUsario = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        email.setText("Dirección de correo:");

        password.setText("Contraseña:");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonNuevoUsario.setText("Nuevo usuario");
        jButtonNuevoUsario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUsarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNuevoUsario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNuevoUsario)
                    .addComponent(jButtonAceptar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String email = jTextFieldEmail.getText();
        char[] password = jPasswordField.getPassword();
        String pass = new String(password);
        if(ValidadorEmail.validarEmail(email)){
	        if (email != "" && pass != "") {
	        	if(control.login(email, pass)) {
	        		usuario = controlUsuarios.selectUsuarioByEmail(email);
	        		usuario.setAficiones(controlUsuarios.selectAficionesByUsuario(email));
	        		List<Usuario> l = controlUsuarios.selectAmigosByEmail(email);
	        		for(Usuario u: l)
	        			usuario.addAmigo(u);
	        		login = true;
	        		this.dispose();
	        		this.setVisible(false);
	        	}
	        }
        }else
       	 JOptionPane.showMessageDialog(null, "Debes introducir un mail" , "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonNuevoUsarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUsarioActionPerformed
    	 String email = jTextFieldEmail.getText();
         char[] password = jPasswordField.getPassword();
         String pass = new String(password);
         if(ValidadorEmail.validarEmail(email)){
	         if (email != "" && pass != "") {
	        	 double latitud = (Math.random()*(41.2- 40)+40);
	        	 double longitud = (Math.random()*(4.5- 3)+3);
	        	 double latitud2 = (Math.random()*(41.2- 40)+40);
	        	 double longitud2 = (Math.random()*(4.5- 3)+3);
	        	 System.out.println("latitud:"+latitud);
	        	 System.out.println("longitud:" + longitud);
	        	 Usuario u2 = new Usuario(email, pass, "", null, null, latitud, longitud, null, null, null, null);
				controlUsuarios.insertUser(u2);
				new AvatarPanel2(null, true, u2, true, controlUsuarios, null).setVisible(true);
	         }
	         else
	        	 JOptionPane.showMessageDialog(null, "Email o contraseña incorrectos" , "Error", JOptionPane.ERROR_MESSAGE); 
         }
         else
        	 JOptionPane.showMessageDialog(null, "Debes introducir un mail" , "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonNuevoUsarioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonNuevoUsario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
	public boolean isLogin() {
		// TODO Auto-generated method stub
		return login;
	}

	public Usuario getUser() {
		// TODO Auto-generated method stub
		return usuario;
	}
}
