/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;

import abd.p1.controller.ListUserController;
import abd.p1.controller.UserController;
import abd.p1.model.CalculadorDistancias;
import abd.p1.model.Usuario;

/**
 *
 * @author adrianpanaderogonzalez
 */
@SuppressWarnings("serial")
public class VentanaPrincipal extends javax.swing.JDialog {

	private UserController controlUsuarios;
	private Usuario u;
	private AvatarPanel2 userPanel;
	private DefaultListModel<Usuario> modelo;
	private ListUserController controlListaUsuarios;
	
    /**
     * Creates new form VentanaPrincipal
     * @param controlUsuarios 
     * @param u 
     */
    public VentanaPrincipal(Frame parent, boolean modal,Usuario u, UserController controlUsuarios, ListUserController controlListaUsuarios) {
    	super(parent,modal);
    	
        this.u = u;
        this.controlUsuarios = controlUsuarios;
        this.controlListaUsuarios = controlListaUsuarios;
        this.jPanelUsuarios = new JPanelUsuario(controlUsuarios, controlListaUsuarios, u, false);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPreguntas = new javax.swing.JPanel();
        jPanelMensajes = new javax.swing.JPanel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);


        jTabbedPane1.addTab("Usuarios", jPanelUsuarios);

        javax.swing.GroupLayout jPanelPreguntasLayout = new javax.swing.GroupLayout(jPanelPreguntas);
        jPanelPreguntas.setLayout(jPanelPreguntasLayout);
        jPanelPreguntasLayout.setHorizontalGroup(
            jPanelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        jPanelPreguntasLayout.setVerticalGroup(
            jPanelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Preguntas", jPanelPreguntas);

        
        JButton btnMarcarTodosComo = new JButton("Marcar todos como leídos");
        
        textArea = new JTextArea();

        javax.swing.GroupLayout jPanelMensajesLayout = new javax.swing.GroupLayout(jPanelMensajes);
        jPanelMensajesLayout.setHorizontalGroup(
        	jPanelMensajesLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelMensajesLayout.createSequentialGroup()
        			.addGroup(jPanelMensajesLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanelMensajesLayout.createSequentialGroup()
        					.addGap(115)
        					.addComponent(btnMarcarTodosComo))
        				.addGroup(jPanelMensajesLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(textArea, GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        jPanelMensajesLayout.setVerticalGroup(
        	jPanelMensajesLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelMensajesLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(textArea, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnMarcarTodosComo)
        			.addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelMensajes.setLayout(jPanelMensajesLayout);

        jTabbedPane1.addTab("Mensajes no leídos", jPanelMensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    

    private javax.swing.JPanel jPanelMensajes;
    private javax.swing.JPanel jPanelPreguntas;
    private JPanelUsuario jPanelUsuarios;
    private javax.swing.JTabbedPane jTabbedPane1;
    private JTextArea textArea;
}
